# 测试环境配置
# 可以去这个网站将 yaml转为json https://json.im/json2/yaml2json.html
---
env: test
port: 4000
session:
  type: mysql
  options:
    secret: rex1234567890
    name: rex_for_nest
    rolling: true
    resave: false
    saveUninitialized: false
  fileStoreOptions:
    path: ./session_file # session存放的目录
    ttl: 7200         # 单位秒
  redisOptions:
    port: 6379
    host: 127.0.0.1
    database: 0
    ttl: 7200         # 单位秒
    prefix: test_
  mysqlStoreOptions: # 使用FileStore老是会报异常，所以在这里使用mysql做为替换。
    database: xn_session
    password: root123!!!
    host: 127.0.0.1
    port: 3306
    user: root
